import { type Customer, type Invoice, type Product } from './types';

export const customers: Customer[] = [
  {
    id: 'cus_1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '123-456-7890',
    address: { street: '123 Main St', city: 'Anytown', state: 'CA', zip: '12345' },
    company: 'Doe Inc.',
  },
  {
    id: 'cus_2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '987-654-3210',
    address: { street: '456 Oak Ave', city: 'Someville', state: 'NY', zip: '67890' },
    company: 'Smith & Co.',
  },
  {
    id: 'cus_3',
    name: 'Innovate LLC',
    email: 'contact@innovatellc.com',
    phone: '555-123-4567',
    address: { street: '789 Tech Park', city: 'Silicon Valley', state: 'CA', zip: '54321' },
    company: 'Innovate LLC',
  },
  {
    id: 'cus_4',
    name: 'Global Exports',
    email: 'support@globalexports.com',
    phone: '555-987-6543',
    address: { street: '101 Trade Center', city: 'Metropolis', state: 'IL', zip: '10101' },
    company: 'Global Exports',
  },
];

export const invoices: Invoice[] = [
  {
    id: 'inv_1',
    invoiceNumber: 'INV-001',
    customerId: 'cus_1',
    issueDate: '2024-06-15',
    dueDate: '2024-07-15',
    items: [
      { id: 'item_1', description: 'Web Development Services', quantity: 10, price: 150 },
      { id: 'item_2', description: 'Logo Design', quantity: 1, price: 500 },
    ],
    taxRate: 0.08,
    discount: 100,
    status: 'Pagada',
  },
  {
    id: 'inv_2',
    invoiceNumber: 'INV-002',
    customerId: 'cus_2',
    issueDate: '2024-07-01',
    dueDate: '2024-07-31',
    items: [{ id: 'item_3', description: 'Marketing Consultation', quantity: 5, price: 200 }],
    taxRate: 0.0,
    discount: 0,
    status: 'Pendiente',
  },
  {
    id: 'inv_3',
    invoiceNumber: 'INV-003',
    customerId: 'cus_3',
    issueDate: '2024-05-20',
    dueDate: '2024-06-20',
    items: [
      { id: 'item_4', description: 'Cloud Server Hosting (Annual)', quantity: 1, price: 1200 },
      { id: 'item_5', description: 'Domain Name Registration', quantity: 2, price: 15 },
    ],
    taxRate: 0.05,
    discount: 50,
    status: 'Vencida',
  },
  {
    id: 'inv_4',
    invoiceNumber: 'INV-004',
    customerId: 'cus_1',
    issueDate: '2024-07-10',
    dueDate: '2024-08-10',
    items: [{ id: 'item_6', description: 'Monthly Retainer - SEO Services', quantity: 1, price: 2500 }],
    taxRate: 0.08,
    discount: 0,
    status: 'Pendiente',
  },
  {
    id: 'inv_5',
    invoiceNumber: 'INV-005',
    customerId: 'cus_4',
    issueDate: '2024-07-05',
    dueDate: '2024-08-05',
    items: [
      { id: 'item_7', description: 'Shipping Container Rental', quantity: 3, price: 300 },
      { id: 'item_8', description: 'Insurance Coverage', quantity: 1, price: 150 },
    ],
    taxRate: 0.02,
    discount: 0,
    status: 'Pagada',
  },
];

export const products: Product[] = [
  {
    id: 'prod_1',
    name: 'Laptop Pro 15"',
    description: 'Potente laptop para profesionales y creativos.',
    price: 1299.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Computadoras',
    stock: 25,
  },
  {
    id: 'prod_2',
    name: 'Smartphone X',
    description: 'El último smartphone con cámara de alta resolución.',
    price: 899.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Celulares',
    stock: 50,
  },
  {
    id: 'prod_3',
    name: 'Auriculares Inalámbricos',
    description: 'Cancelación de ruido y sonido inmersivo.',
    price: 199.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Accesorios',
    stock: 120,
  },
  {
    id: 'prod_4',
    name: 'Monitor UltraWide 34"',
    description: 'Monitor curvo para una experiencia de visualización panorámica.',
    price: 599.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Monitores',
    stock: 40,
  },
  {
    id: 'prod_5',
    name: 'Teclado Mecánico RGB',
    description: 'Teclado para gaming con retroiluminación personalizable.',
    price: 149.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Accesorios',
    stock: 80,
  },
  {
    id: 'prod_6',
    name: 'Smart TV 4K 55"',
    description: 'Televisor inteligente con resolución 4K y HDR.',
    price: 699.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Televisores',
    stock: 30,
  },
  {
    id: 'prod_7',
    name: 'Tablet 10"',
    description: 'Tablet ligera y potente para el día a día.',
    price: 329.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Tablets',
    stock: 60,
  },
];
